### Server Configuration
server:
  port: 8092
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true


### Logging Configuration
logging:
  level:
    io.swagger.models.parameters.AbstractSerializableParameter: ERROR
# https://github.com/springfox/springfox/issues/2776#issuecomment-600405932
# *** https://blog.karatos.in/a?ID=00950-7a1f5c4c-1e88-40e4-b5bb-5244dc110e2f


### Spring Configuration
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: SECRET
            clientSecret: SECRET
          naver:
            clientId: SECRET
            clientSecret: SECRET
            redirectUri: 'http://i6b206.p.ssafy.io:80/main/feed'
            authorizationGrantType: authorization_code
            clientName: naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

  servlet:
    multipart:
      max-file-size: 1000MB
      maxRequestSize: 1000MB
  mvc:
    static-path-pattern: /files/**

  ### Datasource
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3606/together-homt?serverTimezone=Asia/Seoul
    username: ssafy
    password: 1234

  ### JPA
  jpa:
    show-sql: false

    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    properties:
      hibernate:
        format_sql: true

